# Site settings
title: Tongbo Cai - 蔡同波
# description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://caitongbo.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tongbo Cai
# user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: caitongbo@outlook.com
# twitter_username: lorem_ipsum
github_username:  caitongbo
# qq: 461892420
# wechat: ctb461892420
# weibo: 
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
